apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJZMmhsZEdGdU9rTnJlVUF4T1RnMSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: null
  name: quay-io-imagepullsecret
type: kubernetes.io/dockerconfigjson
